sudo: false
language: c

install:
  - git clone --depth 1 https://github.com/sstephenson/bats.git

script:
  - PATH=".:./bats/bin:$PATH" test/run

notifications:
  email: false

before_deploy: "sha1sum javinla > javinla.sha1"
deploy:
  provider: releases
  api_key:
    secure: Sx9e9Y8cRVb7k1fyHnjJ9o2UJWsoQhChjqzS3MWEbMWkUW8GXG0/I6eW7FQBK9jEsKG1OqY7hIOYh33hkfglXVFDI0kxGj9XOEn0arBjwQDbSSZXY7CDPyjBZN+lb+v1MfXgyMKJ4pSwufxtq/NvxcF4VG4jgWv3ZzrNcntzSCU=
  file:
    - javinla
    - javinla.sha1
  skip_cleanup: true
  on:
    repo: nerro/javinla
    tags: true
